import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
    admin: [
        PERMISSIONS.CREATE_USER,

        PERMISSIONS.CREATE_DOCUMENT,
        PERMISSIONS.READ_DOCUMENT,
        PERMISSIONS.UPDATE_DOCUMENT,
        PERMISSIONS.DELETE_DOCUMENT,

        PERMISSIONS.VIEW_CLIENTS,
        PERMISSIONS.VIEW_REPORTS,

        PERMISSIONS.VIEW_PAGOS
    ],
    supervisor: [
        PERMISSIONS.READ_DOCUMENT,
        PERMISSIONS.VIEW_CLIENTS
    ],
    seller: [
        PERMISSIONS.READ_DOCUMENT,
        PERMISSIONS.VIEW_CLIENTS
    ],
};